### ISSUE TITLE
Add Dependencies list

### ISSUE THREAD

**Issue by benkhlifafahmi** [zardus/ctf-tools#121]
create an option where user can install dependencies for all or specific tools before the install

**Comment by zardus** [comment]
Have you looked at `manage-tools -s install $TOOLNAME`? This allows it to use sudo to apt-get (or yum or pacman or whatnot) install dependencies.

**Comment by benkhlifafahmi** [comment]
sorry i missed that :+1: Thanks :1st_place_medal:
