### ISSUE TITLE
python virtualenv

### ISSUE THREAD

**Issue by zardus** [zardus/ctf-tools#13]
Currently, we force the user to create a virtualenv before running manage-tools. Maybe we should have manage-tools automatically create a virtualenv for each tool?

**Comment by crowell** [comment]
hmmm, i dont think this flies for things like pwntools.

if i have that, maybe i'd also like to use it with something else.

**Comment by zardus** [comment]
Yeah, agreed...

We do need a separate python2 and python3 env, though, now that we have a python3-only tool (foresight) :-(
