### ISSUE TITLE
Binwalk: fails to install on Ubuntu 14.10

### ISSUE THREAD

**Issue by subwire** [zardus/ctf-tools#8]
The install failed -- looks like the package installation wasn't done in a writeable location?

Installing collected packages: binwalk
  Running setup.py develop for binwalk
    error: can't create or remove files in install directory

```
The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-8583.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python2.7/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://pythonhosted.org/setuptools/easy_install.html

Please make the appropriate changes for your system and try again.

Complete output from command /usr/bin/python -c "import setuptools, tokenize; __file__='/home/edg/code/ctf-tools/binwalk/binwalk/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
running develop
```

error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the

installation directory:

```
[Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-8583.write-test'
```

The installation directory you specified (via --install-dir, --prefix, or

the distutils default setting) was:

```
/usr/local/lib/python2.7/dist-packages/
```

Perhaps your account does not have write access to this directory?  If the

installation directory is a system-owned directory, you may need to sign in

as the administrator or "root" account.  If you do not have administrative

access to this machine, you may wish to choose a different installation

directory, preferably one that is listed in your PYTHONPATH environment

variable.

For information on other options, you may wish to consult the

documentation at:

  https://pythonhosted.org/setuptools/easy_install.html

Please make the appropriate changes for your system and try again.

---

Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize; **file**='/home/edg/code/ctf-tools/binwalk/binwalk/setup.py'; exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" develop --no-deps failed with error code 1 in /home/edg/code/ctf-tools/binwalk/binwalk
Storing debug log for failure in /tmp/tmp1q6Xkc

**Comment by zardus** [comment]
Check out the last sentence of https://github.com/zardus/ctf-tools/blob/master/README.md#usage
