### ISSUE TITLE
Add zsteg

### ISSUE THREAD

**Issue by CodeMaxx** [zardus/ctf-tools#89]
https://github.com/zed-0xff/zsteg

> detect stegano-hidden data in PNG & BMP

**Comment by 5teven1in** [comment]
can it just install by 
```
gem install zsteg
```

**Comment by CodeMaxx** [comment]
@ss8651twtw That is the normal way to install it. I wanted that a script be added to the repo which would do that automatically

**Comment by zardus** [comment]
In general, a PR is much better than an issue. Otherwise, this'll probably be gotten to eventually, but probably not anytime soon :-)

**Comment by f0rki** [comment]
anyone knows what the `gem` equivalent to `pip install -e` is?
